### ISSUE TITLE
How to load vast with xml, not uri

### ISSUE THREAD

**Issue by WuBingHui** [googleads/googleads-ima-android#100]
hi~
I want to load vast with xml, not uri
Does the IMA SDK provide any way for me to do this?

`<VAST xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="vast.xsd" version="3.0">
...
</VAST>
`

**Comment by Kiro705** [comment]
Hello @WuBingHui ,

This is not demonstrated in the sample apps, but you can use [AdsRequest.setAdsResponse()](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/api/reference/com/google/ads/interactivemedia/v3/api/AdsRequest.html#setAdsResponse(java.lang.String)) to directly set the xml.

Let me know if you have any follow-up questions.

Thank you,
Jackson
IMA SDK team
