### ISSUE TITLE
Video content freezes before playing when postroll is present

### ISSUE THREAD

**Issue by natrubin24** [googleads/googleads-ima-android#109]
Hello,

I have recently onboarded to the IMA SDK for Android to support linear, postroll video ads and am facing an issue with my video content freezing before it plays when an ad is present. 

My implementation uses the `buildForAdsResponse` function to load a pre-fetched VMAP containing a single postroll ad into the player. Through debugging, I see the following two AdEvents occur when the player is opened: 
* CONTENT_RESUME_REQUESTED
* LOADED

I've tested with the IMA provided [sample VMAP Postroll tag](https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/vmap_ad_samples&sz=640x480&cust_params=sample_ar%3Dpostonly&ciu_szs=300x250&gdfp_req=1&ad_rule=1&output=vmap&unviewed_position_start=1&env=vp&impl=s&correlator=), in addition to the actual VMAP that is being fetched, and see the same behavior for both tags.

During the time of those two AdEvents occurring, the player is frozen with the (non-ad) video content paused in the player. After a few seconds, the content begins playing and is followed by the postroll ad. 

Please advise on how I can get rid of the frozen time and let me know if you need additional details.

----------
AdsLoader implementation:
```
    private fun prepareAdPlayer() {
        val activePlayer = getActivePlayer()
        val dataSourceFactory = getDataSourceFactory()
        val playerView = getPlayerView()
        playerView?.player = player

        try {
            adsLoader = ImaAdsLoader.Builder(context)
                .setVastLoadTimeoutMs(getVideoAdLoadTimeout())
                .buildForAdsResponse(getVMAP())
            adsLoader?.setPlayer(player)
        } catch (e: Exception) {
            Log.e(TAG, "Exception thrown while initializing the ad loader: $e")
            doesContainAd = false
        } finally {
            setupActivePlayer(activePlayer, dataSourceFactory, playerView)
        }
    }

    private fun setupActivePlayer(
        activePlayer: SimpleExoPlayer?,
        dataSourceFactory: DataSource.Factory,
        playerView: PlayerView?
    ) {
        val contentMediaSource = createMediaSource(getPlaybackUri(), dataSourceFactory)

          activePlayer?.let{
              it.playWhenReady = true
              it.seekTo(0)
              it.prepare(AdsMediaSource(contentMediaSource, dataSourceFactory, adsLoader, playerView))
              it.addListener(this)
        }
    }
```

**Comment by Kiro705** [comment]
Hello @natrubin24 ,

Thank you for raising this issue. Would it be possible to share:
Which sample app you are modifying?
A video recording of the issue?

When testing with the Advanced Example, I see both CONTENT_RESUME_REQUESTED and LOADED events happening at the start of content playback when selecting the Post-roll option.

Thank you,
Jackson
IMA SDK team

**Comment by natrubin24** [comment]
Hi Jackson,

Thanks for getting back to me. My team isn't modifying one of the sample apps, we have the IMA SDK fully integrated into our application (FireTV app) and based it off of the BasicExample. Attaching a video recording of the issue below.

Please let me know if you have any other questions and how we can move forward debugging this issue.

Thanks!

**Comment by natrubin24** [comment]
https://user-images.githubusercontent.com/117224058/201440622-5fe9de30-ba90-4bb1-aada-1b10c21f675f.mov

**Comment by natrubin24** [comment]
Thanks for pointing me to the correct place! I will repost this in the forum.

Best,
Natalie
