### ISSUE TITLE
Add ExoPlayer2 Sample

### ISSUE THREAD

**Issue by noamtamim** [googleads/googleads-ima-android#11]
Please provide a sample app for using IMA with ExoPlayer2. The new APIs mean GMF is not needed anymore -- maybe just a very thin wrapper around SimpleExoPlayer.

**Comment by ypavlotsky** [comment]
Thanks for the suggestion, we're still investigating our approach with ExoPlayer2.

**Comment by Kiran89kumar** [comment]
Is any update on same?

**Comment by ypavlotsky** [comment]
Hi,

We don't have any updates except to say that we're still looking into the best way to support IMA using Exo v2. Thanks,
--Yury

**Comment by ypavlotsky** [comment]
Please see the [ExoPlayer IMA extension](https://github.com/google/ExoPlayer/tree/release-v2/extensions/ima) for an IMA implementation using ExoPlayer 2.
