### ISSUE TITLE
About macro expansion of tracker URLs when using client-side ad insertion

### ISSUE THREAD

**Issue by hyunwookim-moloco** [googleads/googleads-ima-android#115]
Hi! I have a question of MACRO expansion of Exo Player IMA extension.

I want to fire imp tracker of VAST response by replacing some parts of them.
For example, If the below VAST response is given,

```xml
<vmap:VMAP
		xmlns:vmap="http://www.iab.net/videosuite/vmap" version="1.0">
	<vmap:AdBreak timeOffset="#1" breakType="linear">
		<vmap:AdSource>
			<vmap:VASTAdData>
				<VAST version="3.0">
					<Ad sequence="1">
						<InLine>
							<AdSystem version="1">
								<![CDATA[...]]>
							</AdSystem>
							<AdTitle>
								<![CDATA[...]]>
							</AdTitle>
							<Impression id="Moloco">
								<![CDATA[https://dummy.com/imp?imp_id=abc123&user_id=%%USER_ID%%]]>
							</Impression>
							<Creatives>
								<Creative id="aaaaaD7TvvyX5ZtkIz4eG.j.Uz0Kglh3U7sDROzm" sequence="1">
									<Linear>
										<Duration>00:00:30</Duration>
										<TrackingEvents>
											<Tracking id="Moloco_4q" event="complete">
												<![CDATA[ https://dummy.com/imp?imp_id=abc123&user_id=%%USER_ID%%&event-complete ]]>
											</Tracking>
										</TrackingEvents>
										<VideoClicks></VideoClicks>
										<MediaFiles>
											<MediaFile id="mediafile" delivery="progressive" type="video/mp4" bitrate="700" width="1920" height="1080">
												<![CDATA[......]]>
											</MediaFile>

										</MediaFiles>
									</Linear>
									<CreativeExtensions></CreativeExtensions>
								</Creative>
							</Creatives>
							<Description></Description>
							<Survey></Survey>
							<Extensions></Extensions>
						</InLine>
					</Ad>
				</VAST>
			</vmap:VASTAdData>
		</vmap:AdSource>
	</vmap:AdBreak>
</vmap:VMAP>
```

we want to replace `%%USER_ID%%` to actual user id. 
- .../imp?imp_id=abc123&user_id=`%%USER_ID%%` -> .../imp?imp_id=abc123&user_id=`userid123`

We use ExoPlayer by importing IMA extension.
Could you guide me how can I replace the macro in this case?

**Comment by hyunwookim-moloco** [comment]
Could you guide me on how to log the `imp / view tracker` at ` ExoPlayerExample` project?

**Comment by Kiro705** [comment]
Hello @hyunwookim-moloco ,

I would recommend looking at the [Ad Manager macro guide](https://support.google.com/admanager/answer/2376981) for more information on supported macros. As far as I know the IMA or Ad Manager do no currently support a %%USER_ID%% macro.

Ad Manager does support a number of [URL parameters](https://support.google.com/admanager/answer/10678356). Does anything in that guide help with your use-case?

I am unsure about `imp / view tracker` logging. Do you have any documentation related to that you could share?

Thank you,
Jackson
IMA SDK team

**Comment by hyunwookim-moloco** [comment]
Hi! @Kiro705 !!
Thank you for the kind guide!
What you guided is to do q macro expansion on server-side, but I want to do q macro expansion on client-side.

In the ExoPlayer IMA extension, I confirmed that [view trackers (start, firstQuartile, midpoint, ...) in VAST](https://www.iab.com/wp-content/uploads/2015/06/VASTv3_0.pdf) (section 2.2.5 VAST tracking) are automatically fired. In order to do that, I think IMA extenstion needs to parse VAST at least once.

Could you guide me how to do macro expansion on client-side? 
And also could you give me the code pointer that parses VAST response from Ad Server?
