### ISSUE TITLE
[Feature Request] AdError class: add raw error response body

### ISSUE THREAD

**Issue by thearaks** [googleads/googleads-ima-android#128]
Some VAST servers reply with custom formats to ad requests.
Since this library can't parse all kind of error formats it would be helpful to provide the original response body in the AdError class to let the app parse and handle the error.

**Comment by thearaks** [comment]
Hello @Kiro705,
I think I opened the issue on the wrong project, I actually wanted to request the addition of this feature to the IMA SDK AdError class!
I'll write a post here: https://groups.google.com/g/ima-sdk/

**Comment by Kiro705** [comment]
Sounds good, I will close this issue here.
