### ISSUE TITLE
Can we create a custom SKIP AD button for custom AD UI?

### ISSUE THREAD

**Issue by krackjack234** [googleads/googleads-ima-android#129]
Hi,

We want to create a custom AD UI for android and apple tv platforms.
We want to know if we can create a custom SKIP AD button and use it for skipping ads without impacting any feature (e.g. analytics tracking) 

Kindly let us know

**Comment by Kiro705** [comment]
Hello @krackjack234 ,

Creating a custom skip button or changing the skip button is not supported by the IMA SDK (see the [IMA FAQ](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/faq#13)). If you would like to make a feature request to the IMA SDK team, please add to or create a thread on the [IMA technical forum](https://groups.google.com/g/ima-sdk).

Thank you,
Jackson
IMA SDK team

**Comment by krackjack234** [comment]
hi @Kiro705  thanks for the response. 

When we play a skippable ad on an android tv, we see a full-screen yellow border when the ad view is focused. We wanted to check if we can avoid this border by creating our own custom AD ui keeping the focus border only on the skip button. Is this possible?

Thanks in advance.

**Comment by Kiro705** [comment]
Hello @krackjack234 ,

For support with the IMA Android SDK (not specific to the IMA Android sample apps), we recommend reaching out through the [IMA SDK technical forum](https://groups.google.com/g/ima-sdk).

That being said, is it possible for your app to use the [AdsManager.focus()](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/api/reference/com/google/ads/interactivemedia/v3/api/BaseManager.html#public-abstract-void-focus) call to change the focus? This method will put focus on the skip button if present. If not present, focus is put on interactive elements, including icons or interactive creatives.

If you have additional questions, I would push you to to reach out on the forum for support about your IMA integration.

Thank you,
Jackson
IMA SDK team
