### ISSUE TITLE
How to fetch the skipoffset from AdEvent

### ISSUE THREAD

**Issue by giladna** [googleads/googleads-ima-android#13]
Hi
I try to implement Native Skip button
The issue is we want to query the skipoffset in the vmap

<Linear skipoffset="00:00:05">

is it possible?
10x

**Comment by ypavlotsky** [comment]
Hi Gilad,

This repo is really only for issues relating to our sample apps, for IMA SDK support, please go to the SDK formus: https://groups.google.com/forum/#!forum/ima-sdk. That being said, we only currently expose whether an ad is skippable. (https://developers.google.com/interactive-media-ads/docs/sdks/android/v3/api/reference/com/google/ads/interactivemedia/v3/api/Ad.html#isSkippable())
