### ISSUE TITLE
Is there any way to customize the `Learn More` text? Wanted to add more contextual information?

### ISSUE THREAD

**Issue by mwshubham** [googleads/googleads-ima-android#135]
Hi, @Kiro705 Is there any way to customize the `Learn More` text? Wanted to add more contextual information?

I checked the surface it is created in a `WebView`

![image](https://github.com/googleads/googleads-ima-android/assets/29930308/74d38de9-5cdd-42d5-9844-616a61ea3698)

_Originally posted by @mwshubham in https://github.com/googleads/googleads-ima-android/issues/34#issuecomment-1785092529_

**Comment by mwshubham** [comment]
Let me know your thoughts on this, @Kiro705

**Comment by Kiro705** [comment]
Hello @mwshubham ,

Sorry for the delay on replying to this issue. IMA does not support customizing the ad UI, including the 'Learn more' button. There may be changes to this, allowing customizations in the future, but currently I have no timelines for those changes. You can subscribe to this [IMA technical forum thread](https://groups.google.com/g/ima-sdk/c/VQsVVBvVEPI/m/ZLo0fCVcAQAJ) for updates on Android SDK release.

Please let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team

**Comment by isaacurbina** [comment]
is this still not supported?
