### ISSUE TITLE
Sometines loading is very slow

### ISSUE THREAD

**Issue by yoannFau78** [googleads/googleads-ima-android#136]
Hi,

In some circumstances, ads (even with test ads) are very slow (about 7 seconds...) to load and i have a black screen.

In the logcat, i can see the following error message  : "**Native network handler not initialized.**"

Can you explain me what is the problem ? How can i fix it ?

The SDK version is 3.31.0

Thanks in advance.

**Comment by Kiro705** [comment]
Hello @yoannFau78 ,

Would you be able to give some more information about when/how you are encountering these long load times?

Such as: device type, Android SDK version, physical or emulated device, network type and strength, which IMA sample you are using, and any modifications you've included in the sample.

Knowing those thing, it will be easier to reproduce the issue on my end to help debug it.

Thank you,
Jackson
IMA SDK team
