### ISSUE TITLE
[Companion] The click was ignored because no browser was available

### ISSUE THREAD

**Issue by victor-munoz** [googleads/googleads-ima-android#138]
Hello, 

On the `AudioPlayerExample`, when the companion image is pressed, nothing happens, and the following message can be read in the Logcat: 

`The click was ignored because no browser was available.`

How can I make the companion image clickable and open the companion ad URL?

**Comment by Kiro705** [comment]
Hello @victor-munoz ,

Thank you for raising this issue, I was able to reproduce the behavior you are describing.

This is an issue specific to a few recent version of the IMA SDK. You can fix it by adding the following to your `AndroidManifest.xml`:

```
<queries>
      <intent>
          <action android:name="android.intent.action.VIEW" />
          <data android:scheme="https" />
      </intent>
      <intent>
          <action android:name="android.intent.action.VIEW" />
          <data android:scheme="http" />
      </intent>
  </queries>
```

There is more info in the [IMA Android getting started guide](https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side#add-intent-declarations). I did test the fix in the sample app, and saw clickthrough work. Please let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team
