### ISSUE TITLE
not seeing impression event in ima-android adEventType 

### ISSUE THREAD

**Issue by krishna-saini** [googleads/googleads-ima-android#139]
impression event Fires when the impression URL has been pinged.

This is present in ima-HTML5 (https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/reference/js/google.ima.AdEvent)

but i am not seeing it ima-android (https://developers.google.com/interactive-media-ads/docs/sdks/android/client-side/api/reference/com/google/ads/interactivemedia/v3/api/AdEvent.AdEventType)

**Comment by Kiro705** [comment]
Hello @krishna-saini ,

Currently there is no Android IMA IMPRESSION ad event. If you would like to make a feature request, I would recommend making a post on the [IMA technical forum](https://groups.google.com/g/ima-sdk).

The issues queue here is primarily for issue specific to the IMA sample apps.

Thank you,
Jackson
IMA SDK team
