### ISSUE TITLE
Lock the device while ad loading -> ad + content will play in background

### ISSUE THREAD

**Issue by giladna** [googleads/googleads-ima-android#14]
Hi,

I am using this adTag: 
"http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&cust_params=sample_ar%3Dpremidpostpodbumper&cmsid=496&vid=short_onecue&correlator=%22"

looks like if LOADED is received while app  is in backGround need to pause the adManager and set a flag for this case 
and onResume if flag is on then resume()
clean the flag in all relevant cases 

BR
Gilad

**Comment by ypavlotsky** [comment]
Hi Gilad,

Which sample are you seeing this with?

--Yury

**Comment by giladna** [comment]
Advanced

**Comment by giladna** [comment]
PRE_ROLL_NO_SKIP(
            "http://rmcdn.2mdn.net/MotifFiles/html/1248596/android_1330378998288.mp4",
            "LOCK_TEST",
            "http://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=xml_vmap1&unviewed_position_start=1&cust_params=sample_ar%3Dpremidpostpodbumper&cmsid=496&vid=short_onecue&correlator=%22",
            R.drawable.thumbnail1,
            false),

**Comment by giladna** [comment]
hi Yuri,
Any update for this?

**Comment by giladna** [comment]
Dear Team any best practice what what should be done in the above case?

**Comment by ypavlotsky** [comment]
Sorry for the delay, for general IMA implementation issues (not bugs / features in the samples) please use our [support forum](https://groups.google.com/forum/#!forum/ima-sdk), as you'll get a response much much quicker. Thanks!

--Yury

**Comment by giladna** [comment]
@ypavlotsky 
Lock the device while ad loading -> ad + content will play in background
Actually this is reproduced in the demo app 
it does looks like a bug for me  

Regards,
Gilad
