### ISSUE TITLE
Ads getting stuck in Buffering state

### ISSUE THREAD

**Issue by Anas-mirza912** [googleads/googleads-ima-android#141]
I am encountering an issue with the pre-roll ads in ExoPlayer. Occasionally, ads become indefinitely stuck in buffering mode after approximately 3-4 seconds of playback in the ExoPlayer. Despite the ad controls being visible, the ad fails to resume playback.

Furthermore, I have noticed that in certain instances, the player screen turns black while the ad volume remains audible, subsequently leading to the ad becoming stuck in buffering mode.

**Comment by Kiro705** [comment]
Hello @Anas-mirza912 ,

Would you be able to provide steps to reproduce the issues you are experiencing?

Once I have that, I'll be able to look into a fix for the ExoPlayer sample app.

Thank you,
Jackson
IMA SDK tea
