### ISSUE TITLE
Ad restarts when app is resumed from background instead of resuming

### ISSUE THREAD

**Issue by Anas-mirza912** [googleads/googleads-ima-android#146]
When the user presses the home button to put the app in the background and then resumes the app, the ad restarts automatically. However, according to the user experience, the ad should resume in that case rather than restart.

Could someone please investigate and address this behavior?

**Comment by Kiro705** [comment]
Hello @Anas-mirza912 ,

The BasicExample is a limited example app showcasing minimal steps to set up the IMA Android SDK. For a more complete player set up, I recommend looking at either the AdvancedExample or ExoPlayerExample. Both of those should resume ads and content at the correct place after backgrounding the app.

Please let me know if you have any additional questions.

Thank you,
Jackson
IMA SDK team
