### ISSUE TITLE
CLI build fails with TransformException as of SDK version 3.7.0

### ISSUE THREAD

**Issue by rzimmer** [googleads/googleads-ima-android#15]
Hi there,

we've just updated to the newest SDK version 3.7.0. Now, when running our build job on Jenkins or locally with `gradlew clean assembleDebug` we get the following, reproduceable build error:

```
:app:transformClassesWithJarMergingForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/apache/commons/lang3/ObjectUtils.class
```

```
:app:transformClassesWithJarMergingForSprylabServerDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: org/apache/commons/lang3/tuple/Pair.class
```

Building from Android Studio does work as there might be a different build mechanism for Instant Run that somehow hides this problem.

After some research, I found an explanation that makes sense to me for what's wrong.
With the newest update, some `commons-lang3` classes are de-obfuscated (as noted in the release history) and thus producing a conflict with our declared dependency to `commons-lang3` resulting in the different duplicate class error.

I see two solutions for this:
Either the SDK declares a dependency to `commons-lang3` without packaging it into the SDK's jar, so the Gradle dependency resolution can take care of everthing. Or the packaged `commons-lang3` should live in a different namespace, so there are no conflicting class files. I'd prefer the first option as it is more _the Gradle way_.

PS: We are using retrolambda, but didn't had any build issues before the update to 3.7.0.

**Comment by shawnbuso** [comment]
Hey there,

Thanks for all the info - could you post this on our [forum](https://groups.google.com/group/ima-sdk)? You'll get a much quicker turnaround for support issues posted there.

Thanks!
Shawn Busolits
IMA SDK Team
