### ISSUE TITLE
Vmap is not working properly - Skipping some ads

### ISSUE THREAD

**Issue by tuncaulubilge** [googleads/googleads-ima-android#16]
Hi,

I'm testing the sample ad with sample vmap urls taken from google's sample vmap tags https://developers.google.com/interactive-media-ads/docs/sdks/android/tags

Using VMAP - Pre-roll Single Ad, Mid-roll Optimized Pod with 3 Ads, Post-roll Single Ad (bumpers around all ad breaks)   - https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostoptimizedpodbumper&cmsid=496&vid=short_onecue&correlator=

Using the sample player and the vmap provided above, I encountered multiple cases where the player skips current ads in pre-roll and mid-rolls. Sometimes the bumpers are not played at all, and other times 2nd or 3rd ads are skipped in the mid-roll pod ads. The issue doesn't happen everytime but if you try it for a few times, you should encounter the same issue. I'm using Google Pixel XL as the test device.

**Comment by ypavlotsky** [comment]
Which sample are you seeing this with?

**Comment by tuncaulubilge** [comment]
BasicExample 3.2, changed the adUrl to the vmap provided above

**Comment by tuncaulubilge** [comment]
Thanks. Should I escalate the issue to Google Support or is this issue sufficient? 

We are encountering this issue on our production app, and it's highly affecting our ad revenue. Can you provide an estimation for a solution so I can inform our product team?

**Comment by shawnbuso** [comment]
We can run with this from here - thanks!

**Comment by ypavlotsky** [comment]
Closing this out as there hasn't been any activity here in a while. Feel free to comment if this is still an issue.

**Comment by tuncaulubilge** [comment]
Well, the problem is not fixed yet. We just accepted our fate with randomly skipping ads :)

**Comment by ypavlotsky** [comment]
Does this still happen with the latest 3.8.2. SDK?

**Comment by giladna** [comment]
@ypavlotsky 
We have this issue as well and it is critical for our customers
it is easy to reproduce in the BasicSample
I will be glad to help or give more information

we have file an issue to the support team No.  9-1413000019901

10x
Gilad.

**Comment by ypavlotsky** [comment]
Thanks for updating us on the issue, @giladna. This does appear to be an underlying SDK issue, not something wrong with the samples and I'll reply here when I have any further updates.

**Comment by maxTanquerel** [comment]
Any new on this issue ? I have the same issue

**Comment by Kiro705** [comment]
Hi all,

Is this issue still reproducible?

I tested with the [latest sample release](https://github.com/googleads/googleads-ima-android/releases/tag/3.25.1-0) and during 5 tests I saw 2 pre-roll (ad + bumper) and 5 mid-rolls (bumper + ad x3 + bumper).
