### ISSUE TITLE
Provide IMA DAI example

### ISSUE THREAD

**Issue by takn** [googleads/googleads-ima-android#18]
[In this page](https://developers.google.com/interactive-media-ads/docs/sdks/android/dai-quickstart#prerequisites) a samplehls implementation for DAI is mentioned in the Prerequisites but the page doesn't contain a link to it. looking in the repo, it doesn't seem to exist. Can you please provide this sample?

**Comment by shawnbuso** [comment]
Hey there,

If you're in our closed beta you can get the samples through your TAM. Let me know if you have any other questions!

Thanks,
Shawn

**Comment by ypavlotsky** [comment]
You can now find DAI Android samples in our [GitHub repo](https://github.com/googleads/googleads-ima-android-dai).
