### ISSUE TITLE
Memory leak in AdDisplayContainer

### ISSUE THREAD

**Issue by pwiniars** [googleads/googleads-ima-android#20]
Hi,

When you start to play the ad and then exit the activity with back button, the memory leak occurs. Looks like the container view provided by the activity to display ad still holds the context. When you perform mAdsManager.destroy() inside activity onDestroy() method, then leak is gone. But this solution creates another problem - it looks like mAdsManager.destroy() method invokes AdEvents related to CONTENT_RESUME_REQUEST and ALL_ADS_COMPLETED. As a result the content player is initialized again at the end of the activity lifecycle.

I've managed to recreate the leak by using BasicExample. 

[com.google.ads.interactivemedia.v3.samples.videoplayerapp_2017.05.23_14.41.hprof.zip](https://github.com/googleads/googleads-ima-android/files/1022235/com.google.ads.interactivemedia.v3.samples.videoplayerapp_2017.05.23_14.41.hprof.zip)
[leak_trace.txt](https://github.com/googleads/googleads-ima-android/files/1022247/leak_trace.txt)

**Comment by shawnbuso** [comment]
Thanks for the report - we'll take a look at this one.

**Comment by ypavlotsky** [comment]
Closing this out as there hasn't been any activity for a while. Feel free to reopen if this is still an issue.
