### ISSUE TITLE
IMA extension: ad tag url requested twice

### ISSUE THREAD

**Issue by jeevarajp** [googleads/googleads-ima-android#25]
I am using exoplayer version 2.5.3 and IMA sdk version 3.7.4

I followed exactly same steps in https://medium.com/google-exoplayer/playing-ads-with-exoplayer-and-ima-868dfd767ea blog to play advertisements. But while debugging it with fiddler (http://www.telerik.com/fiddler) I saw that ad tag url was requested twice.

I also understood that ad tag url is requested by IMA sdk itself two times.  Could you please advise me whether IMA sdk intentionally request this ad tag url twice? or Is that a bug in IMA sdk?

Thanks.

**Comment by jeevarajp** [comment]
@ypavlotsky Please give me your comments.

**Comment by ypavlotsky** [comment]
Closing this out as there hasn't been any activity in a while. If this is still happening, feel free to reopen.
