### ISSUE TITLE
IMA extension: Ads playback without internet connection

### ISSUE THREAD

**Issue by jeevarajp** [googleads/googleads-ima-android#26]
I am using exoplayer (with IMA) version 2.6.0

I followed exactly same steps in https://medium.com/google-exoplayer/playing-ads-with-exoplayer-and-ima-868dfd767ea blog.

I have video content and advertisement content (ad xml and ad video) in my local intranet. I connected my local intranet wifi from a mobile, so that I can access my video content and ads content without internet.

If I enable internet access to this wifi connection and try to run this application then ads in my local intranet are playing fine.

But If I disable internet access to this local intranet wifi and try to run this application then my ads (which is in local intranet) keep on buffering and not playing at all. When I try to fiddler my mobile traffic I see that IMA sdk tries to request below urls to play ads.

https://imasdk.googleapis.com
https://pagead2.googlesyndication.com

So my question is "Does internet access is necessary to play advertisement using IMA sdk?". Is there any alternative way to play ads without internet connection?

Thanks.

**Comment by ypavlotsky** [comment]
Hi,

This forum is really for our Android samples, general IMA SDK issues should be taken to our [Google group.](https://groups.google.com/forum/#!forum/ima-sdk).

With that said, the IMA SDK is going to need to reach out to various servers to work, so it's not possible to use it in offline mode.
