### ISSUE TITLE
How we will manage focus on Skip button in FireTV?

### ISSUE THREAD

**Issue by shailesh2208** [googleads/googleads-ima-android#27]
I am using IMA SDK in amazon fire tv, but unable to manage focus on skip button.
How can we manage focus on Skip button in Fire TV?

**Comment by ypavlotsky** [comment]
Hi there,

This repo is for the IMA Android samples. For general IMA SDK questions, please head over to our [forums](https://groups.google.com/forum/#!forum/ima-sdk), and someone will take a look at your issue ASAP. Thanks!
