### ISSUE TITLE
Make private private ImaSdkFactory() public or anyhow mockable.

### ISSUE THREAD

**Issue by AlienAsRoger** [googleads/googleads-ima-android#30]
I'm writing a unit tests around our IMA integration, and one of the component is 

`com.google.ads.interactivemedia.v3.api.ImaSdkFactory`
which has this code inside:

```
public class ImaSdkFactory {
    private static ImaSdkFactory instance;

    private ImaSdkFactory() {
    }

    public static ImaSdkFactory getInstance() {
        if (instance == null) {
            instance = new ImaSdkFactory();
        }

        return instance;
    }
```

When I try to mock it in my unit test:

```
ImaSdkFactory imaSdkFactory = mock(ImaSdkFactory.class);
```

I got the following error:
```
org.mockito.exceptions.base.MockitoException: 
Mockito cannot mock this class: class com.google.ads.interactivemedia.v3.api.ImaSdkFactory.

Mockito can only mock non-private & non-final classes.
If you're not sure why you're getting this error, please report to the mailing list.


Java               : 1.8
JVM vendor name    : JetBrains s.r.o
JVM vendor version : 25.152-b01
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 1.8.0_152-release-1024-b01
JVM info           : mixed mode
OS name            : Mac OS X
OS version         : 10.13.3


Underlying exception : java.lang.IllegalArgumentException: Could not create type
```

Is it possible to change constructor of this class to package private or public?

I found this talk https://www.youtube.com/watch?v=-FRm3VPhseI&index=4&list=PLED6CA927B41FF5BD where Misko Hevery talks exactly about this case.

Thank you!

**Comment by ypavlotsky** [comment]
Hi,

This repo is only for the samples for the IMA SDK for Android. For issues related to the SDK itself, please post on the [SDK forums](https://groups.google.com/forum/#!forum/ima-sdk). Thanks!

**Comment by AlienAsRoger** [comment]
Oh, I'm sorry. Thank you!
