### ISSUE TITLE
IMA Ad RESUME callback doesn't get called in addAdEventListener()

### ISSUE THREAD

**Issue by firozanawar** [googleads/googleads-ima-android#31]
I am trying to implement IMA Ad. Everything working except one issue. When i start my video the Ad comes and while playing Ad when i press home button the app goes to background. When i return from background the text with timer (i.e "You can skip this ad in 4). From which timer counter i have put the app in background the timer count freezes. i mean to say text should be You can skip this ad in 4 and then You can skip this ad in 3, You can skip this ad in 2 and at last You can skip this ad in 1. But in my case "You can skip this ad in 4" freezes when i come from background. 

Help 'll be appreciated.

THANK YOU !!

**Comment by ypavlotsky** [comment]
Hi there,

I'm not seeing this issue in the BasicExample or AdvancedExample. Are you using one of these as a reference? They both properly handle pausing and unpausing when the Activity is backgrounded.
