### ISSUE TITLE
Remove  "learn more text"

### ISSUE THREAD

**Issue by ummerakbar45** [googleads/googleads-ima-android#34]
Hi 

I have implemented IMA sdk in my video app, but I am not sure how to hide/remove learn more icon.
Please guide me how can I remove that.
I tested app with demo vast tag url and ads were seen sometimes only

**Comment by Kiro705** [comment]
Hello @ummerakbar45 ,

The 'Learn more' button is not removable for IMA mobile SDKs. This is how users access the click-through url on mobile.

Please let me know if you have any other questions. Feel free to reopen this issue if you do.

**Comment by mwshubham** [comment]
Hi @Kiro705 Is their any way to customize the say to add more contextual information?
