### ISSUE TITLE
Issue when Run advanced example 

### ISSUE THREAD

**Issue by ummerakbar45** [googleads/googleads-ima-android#35]
hi
When run sample app got this error

**Failed to resolve: play-services-basement**

**Comment by Kiro705** [comment]
Hello @ummerakbar45 ,

I tested the Advanced Example with the [latest release](https://github.com/googleads/googleads-ima-android/releases/tag/3.25.1-0) and did not encounter this error.

Please feel free to reopen this issue if it is still reproducible on your end.
