### ISSUE TITLE
Ad skipped on pause

### ISSUE THREAD

**Issue by davibe** [googleads/googleads-ima-android#37]
IMA sdk version: **3.10.2**, Android version: does not matter
The issue is probably similar to #16 

It's reproducible using this vast (official example): https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpostlongpod&cmsid=496&vid=short_tencue&correlator=

How to reproduce: Use the previous url as VAST for any video. Wait for the first midroll (happens at 10 seconds in the video and it contains 5 video ads), wait for the second video ad and try to pause the ad `mAdsManager.pause()`. The pause will skip the 2nd ad entirely instead of just pausing it. This happens to the 4th ad as well 

The Basic example exhibits this behaviour. The ADVANCED example however manages to WORK because it's using a custom player implementation, not the (recommended) sdk on one as the Basic example does. You can also reproduce the issue in the Advanced example by commenting out the following line (using the sdk player instead of the custom one)

`mAdDisplayContainer.setPlayer(mVideoPlayerWithAdPlayback.getVideoAdPlayer());`

I attach the version of the Advanced example that exhibits the wrong behaviour. In this example run the test 4th case named `BUG EXAMPLE` and tap the ad to play/pause it as described before
[AdvancedExample.zip](https://github.com/googleads/googleads-ima-android/files/2737162/AdvancedExample.zip)

Also note that using older SDKs as 3.9.0, and 3.9.4, pausing the player results in the inability to receive additonal TAPPED events, which is the event I use to play/pause the ad..

**Comment by Kiro705** [comment]
Hello @davibe ,

I tried to reproduce this issue using the steps you provided on the [latest sample version](https://github.com/googleads/googleads-ima-android/releases/tag/3.25.1-0), but was not able to see the ad being skipped.

Please feel free to reopen this issue if it is still reproducible on your end.
