### ISSUE TITLE
AD "controls" are lost on midroll ad skip

### ISSUE THREAD

**Issue by davibe** [googleads/googleads-ima-android#38]
IMA versione: **3.10.2**, Android version: does not matter

We have created a VMAP that contains a midroll at 10s in the video. The midroll ad is composed of 2 videos. The first two are skippable.

Configuring the Advanced example to play such midroll we can reproduce the following bug.
Skipping an AD will correctly show the next one but from tha moment on the AD video is shown without the usual ad controls around it (ad controls = black gradient of the header, learn more button, ad counter, skip button. Additionally, it looks like some events are not emitted anymore (ad progress, tapped, some others..)

The normal IMA behaviour can be recovered by programmatically scheduling `mAdsManager.pause()` and `mAdsManager.resume()` at 100 ms delay after the next `AdEvent.LOADED` event.
This is however a bad workaround.

This looks a bit related to #37 because it looks like the internal ima ad player is getting confused and it stops sending events.

I attach the project that can be used to reproduce this issue. Note that because it happens randomically just like #37 it is not always reproducible. Some devices exhibit it way more often (like Samsung SM-G950F). Because of this I will also try to attach a video of the bug being reproduced with the sample project.

[AdvancedExample.zip](https://github.com/googleads/googleads-ima-android/files/2741668/AdvancedExample.zip)

https://youtu.be/4OSzPu_8X40

**Comment by Kiro705** [comment]
Hello @davibe ,

Is this issue still reproducible on your end? If so can you please share the ad tag with multiple mid-roll skippable ads for our team to debug with.
