### ISSUE TITLE
AudioTrack leak

### ISSUE THREAD

**Issue by davibe** [googleads/googleads-ima-android#39]
IMA sdk version: 3.10.2, Android version: does not matter

There seems to be an AudioTrack leak.  If I profile the memory of my application I can see multiple AudioTrack elements alive. They are kept alive by a reference cycle with PlayerBase$1. See screenshot

![screenshot 2019-01-15 14 37 06](https://user-images.githubusercontent.com/123929/51183922-0efae300-18d3-11e9-82e4-c15e6003ac6b.png)

The problems is that after a few (many runs) the main player of my application will fail to initialize because of AudioTrack initialization error which is caused by the fact that there are too many audio tracks active.

**Comment by Kiro705** [comment]
Hello @davibe ,

A number of enhancements have been made to the Android IMA SDK to prevent memory leaks since you first posted your issue, and I believe that this has been addressed.

If this is still occurring, please feel free to reopen the issue.
