### ISSUE TITLE
VAST tag time out issue

### ISSUE THREAD

**Issue by ummerakbar45** [googleads/googleads-ima-android#41]
Hi
I am facing vast media file time out issue on most of vast tag urls. 
I have implemented exactly as mentioned in the document but still, I am getting this issue.
One thing to confirm, the issue is not in vast tag URLs as I  tested with many vast tag URLs which are working fine on ioS.
sdk: Android

**Comment by Kiro705** [comment]
Hello @ummerakbar45 ,

Are there any other steps to reproduce this issue? Currently, I am not seeing time-out issues in the Android sample apps.

Please reopen this issue if it is still reproducible.
