### ISSUE TITLE
VAST media file time out issue

### ISSUE THREAD

**Issue by ummerakbar45** [googleads/googleads-ima-android#42]
Hi issue from your side
https://search.spotxchange.com/vast/2.0/85394?VPI=MP4&app[domain]=[REPLACE_ME]&app[bundle]=[REPLACE_ME]&player_height=[FT_PLAYER_HEIGHT]&player_width=[FT_PLAYER_WIDTH]&media_transcoding=low&device[ifa]=FIRETV_ADS_TRACKING_ID&device[dnt]=FIRETV_ADS_TRACKING_ENABLED&app[name]=[REPLACE_ME]&ip_addr=[REPLACE_ME]&device[ua]=FIRETV_ADS_USER_AGENT&device[make]=[REPLACE_ME]&device[model]=[REPLACE_ME]

the above vast tag url does not work in advanced demo app provided by u.

I am getting vast tag time out issue @ypavlotsky @ericleich @ypavlotsky

**Comment by Kiro705** [comment]
Hello @ummerakbar45 ,

I was able to see successful ad playback using your sample tag in the [latest version of the samples](https://github.com/googleads/googleads-ima-android/releases/tag/3.25.1-0). If this is still reproducible on your end, please feel free to reopen this issue.
