### ISSUE TITLE
How can we play movie in one view and Ad in other view.

### ISSUE THREAD

**Issue by ummerakbar45** [googleads/googleads-ima-android#43]
Hi 

I am able to run a basic app and it works fine for me.
Can I provide any Frame layout as an AdContainer like we provide in Advanced Example?
My requirement is play Movie in one view and Ads in other view and I don't need custom playAdbacks. @dberlin @ericleich @ypavlotsky

**Comment by zhangchuangtao** [comment]
You can set two video player.
One to play movie,the other play the Ad.
You can switch the player view in the  CONTENT_PAUSE_REQUESTED and CONTENT_RESUME_REQUESTED event.

**Comment by Kiro705** [comment]
Hello @ummerakbar45 ,

Were you able to solve this issue? Please reopen if you would still like assistance.
