### ISSUE TITLE
AdSense always errors out with "VAST response document is empty"

### ISSUE THREAD

**Issue by egor-n** [googleads/googleads-ima-android#44]
The AdSense ads never load and always error out with the following error:

> The VAST response document is empty.

Should the test ad tag be updated to something else?

<img src="https://user-images.githubusercontent.com/378493/57262767-71aef080-7022-11e9-8b7e-bcc34df83b33.png" height=350px/>

**Comment by Kiro705** [comment]
Hello @egor-n ,

I believe the AdSense tag has been removed from the Advanced Example. Please feel free to reopen this issue if I am missing something.
