### ISSUE TITLE
new commit have issue cannot find symbol callback.onContentComplete()

### ISSUE THREAD

**Issue by vantien1401** [googleads/googleads-ima-android#51]
VideoPlayerWithAdPlayback.java:240: error: cannot find symbol callback.onContentComplete();
symbol:   method onContentComplete()

**Comment by Kiro705** [comment]
Hello @vantien1401 ,

I tested the sample apps in the [latest release](https://github.com/googleads/googleads-ima-android/releases/tag/3.25.1-0), and was unable to reproduce this error.

If you are able to reproduce it still, please reopen this issue with steps on how to reproduce.
