### ISSUE TITLE
Why does the post-roll invalid?

### ISSUE THREAD

**Issue by zhangchuangtao** [googleads/googleads-ima-android#52]
I download the Example.When I use the AdvancedExample project to test the Post-roll,but,it seems to be invalid.

**Comment by Kiro705** [comment]
Hello @zhangchuangtao ,

I tested the post-roll ad in the [latest release](https://github.com/googleads/googleads-ima-android/releases/tag/3.25.1-0) of the AdvancedExample and I was not able to reproduce the error.

If you are still able to reproduce this, please reopen this issue with steps to reproduce.
