### ISSUE TITLE
 Can't find method onContentComplete();

### ISSUE THREAD

**Issue by mshenawy22** [googleads/googleads-ima-android#55]
This happened straight after I compiled the Advanced Example straight from github
file : VideoPlayerwithPayback.java
Line : 240
 callback.onContentComplete();

**Comment by highfly22** [comment]
Update IMA to the latest version.

**Comment by mshenawy22** [comment]
It's already the latest versionOn 23 Jul. 2020 9:01 am, highfly22 <notifications@github.com> wrote:
Update IMA to the latest version.

**Comment by Kiro705** [comment]
Hi @mshenawy22 ,

Are you still able to reproduce this using this issue in the[latest release](https://github.com/googleads/googleads-ima-android/releases/tag/3.25.1-0)? In my attempts to reproduce, I did not see this error.

If you are still encountering this issue, please reopen this issue with any steps needed to reproduce.
