### ISSUE TITLE
Ima sdk from version 3.13.1 to latest not working with exoplayer. Webview with skip ad button is not displayed.

### ISSUE THREAD

**Issue by Grzelazny** [googleads/googleads-ima-android#56]
Hi,
I updated ima sdk from 3.11.1 to latest version and after that on displayed ad i don't have webview with ads count, skip button and learn more text.
Looks line whole layer is not displayed. 
I checked by debugger and webview in IMA SDK is created and content is loaded to webview without errors. 
I tested this also with chrome debugger and i see loaded javascript without any errors on console. (Only missing favicon)

After long research i not found any article or post that can give any information about reason of that. 

I also compared out project with Advanced sample and looks like i have similar parts with ad loading, attaching it to views. 
Because webview is not visible i have error from vast that i reached timeout 8 seconds and my ad is stopped after that. 

This problem impact many applications in our mobile company group, that use player module, so this is important to me to fix this. Player displays several milions ads by month.

I have updated project to androidx.
I also tested this with several versions of exoplayer and i have the same result. 
Here we have my logs:
[logs-exoplayer-demo-app.txt](https://github.com/googleads/googleads-ima-android/files/4897741/logs-exoplayer-demo-app.txt)
I just open video, ad is displayed, but without webview layer. After 8 seconds ad is stopped and video continue play.
<img width="545" alt="player-layout" src="https://user-images.githubusercontent.com/6311922/87058290-31d83000-c208-11ea-975f-7f993594e73f.png">
Here is my player layout.
I checked on obfuscated AdLoader on debug and i don't have any error during make request. (I see before request layout is tested that is ok)

I'm not sure what additional information i can provide. 
Regards,
Grzegorz Małopolski

**Comment by nikhilcn** [comment]
Facing the same issue when trying to play using Texture View, after 8 seconds the playback stops. Error code is 402 and of type PLAY.
@Grzelazny - Have you found a workaround?

**Comment by Grzelazny** [comment]
Hi, my colleague found reason of this issue. 
On this new sdk we need to create TimerTask like in advanced example and call callback.onAdProgress() method manually.
