### ISSUE TITLE
IMA SDK Ads and picture in picture mode.

### ISSUE THREAD

**Issue by Amro-Hamzeh** [googleads/googleads-ima-android#66]
Hello, I'm running into the following issue with IMA SDK v 3.21.0 and Picture in Picture mode in our Android App. Was reproduced on multiple devices. Steps is as follows : 
1- In Player switch to picture in picture mode 
2- While in picture in picture mode mid roll ad plays 
3- Using the picture in picture mode close button(Android OS one), but the Ad audio still plays, won't end unless we kill the application from the application stack.

Few notes to add : 
* The Application have multiple activities layer, in this case Main into Player.
* The Player activity lifecycle reaches Pause then Stop then Destroy (as expected) after clicking the picture in picture close button, in Destroy we call adLoader.release() and adsManager.destroy on our AdsLoader and AdsManager instances, and I verified both lines are called successfully
* Same exact scenario with normal video play(no ads, just normal content) the video will stop playing as expected, so it's only an ad issue
* If we were to click on the application in the applications list background stack, it will open Main Activity, not Player Activity(expected behavior on closing picture in picture for our app structure).
* We're using exoplayer for video playback. 

Thank you for all your help.

**Comment by Kiro705** [comment]
Hello @Amro-Hamzeh ,

Thant you for reaching out. Since this issue is not specific to the IMA Android samples apps, I would recommend reaching out on the [IMA technical forum](https://groups.google.com/g/ima-sdk/) for issues specific to the IMA SDK.

Please feel free to reopen this issue, if it is specific to the Android sample apps.
