### ISSUE TITLE
Logging  ad errors 

### ISSUE THREAD

**Issue by giladna** [googleads/googleads-ima-android#72]
Hi

Could you please add Logging for ad error and ad events in sample so observing ad tag problem reason can be more easier?

Example:
```
// Create an AdsLoader.
    adsLoader = new ImaAdsLoader.Builder(/* context= */ this).
            setAdErrorListener(adErrorEvent -> Log.e("AD_ERROR", adErrorEvent.getError().getMessage())).build();
```

**Comment by Kiro705** [comment]
Hello @giladna ,

Thank you for your input. I will look to add this log into the next release of the Android IMA samples.

Jackson
IMA SDK team

**Comment by Kiro705** [comment]
Hello @giladna ,

It looks like these listeners may already be set in the Advanced Example.

[Ad error here](https://github.com/googleads/googleads-ima-android/blob/master/AdvancedExample/app/src/main/java/com/google/ads/interactivemedia/v3/samples/videoplayerapp/VideoPlayerController.java#L172-L180) and [ad events here](https://github.com/googleads/googleads-ima-android/blob/master/AdvancedExample/app/src/main/java/com/google/ads/interactivemedia/v3/samples/videoplayerapp/VideoPlayerController.java#L88-L95).

Are there events not covered here that you would like to see logged?
