### ISSUE TITLE
IllegalStateException Call to playAd without appropriate call to loadAd first.

### ISSUE THREAD

**Issue by linguokun1** [googleads/googleads-ima-android#75]
Hi,
I encouter the follow exception, this exception occur 1634 times and make 3% users' app crash.
Please help me Thanks.

Fatal Exception: com.google.ads.interactivemedia.v3.internal.kg
       at com.google.ads.interactivemedia.v3.internal.jo.C(jo.java:14)
       at com.google.ads.interactivemedia.v3.internal.lt.C(lt.java:3)
       at com.google.ads.interactivemedia.v3.internal.fj.stopAd(fj.java:8)
       at com.google.ads.interactivemedia.v3.internal.el.d(el.java:3)
       at com.google.ads.interactivemedia.v3.internal.ee.s(ee.java:3)
       at com.google.ads.interactivemedia.v3.internal.ee.e(ee.java:126)
       at com.google.ads.interactivemedia.v3.internal.ek.d(ek.java:5)
       at com.google.ads.interactivemedia.v3.internal.eh.shouldOverrideUrlLoading(eh.java:2)
       at android.webkit.WebViewClient.shouldOverrideUrlLoading(WebViewClient.java:83)
       at n4.g(n4.java:1)
       at org.chromium.android_webview.AwContentsClientBridge.shouldOverrideUrlLoading(AwContentsClientBridge.java:14)
       at android.os.MessageQueue.nativePollOnce(MessageQueue.java)
       at android.os.MessageQueue.next(MessageQueue.java:326)
       at android.os.Looper.loop(Looper.java:160)
       at android.app.ActivityThread.main(ActivityThread.java:6718)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by linguokun1** [comment]
class GoogleAdPlayer : AdPlayer {
    private val TAG = "GoogleAdPlayer"
    private lateinit var adContainer: ViewGroup
    private lateinit var adPlayerListener: AdPlayerListener
    private var overlayViewList: List<View>? = null
    private var adsLoader: AdsLoader? = null
    private var adsManager: AdsManager? = null
    private var isPlaying = false
    private var currentAdEvent: AdEvent? = null
    private var displayContainer: AdDisplayContainer? = null
    private var ad: Ad? = null
    private var loadingTimeoutJob: Job? = null

    private val imaSdkSettings: ImaSdkSettings by lazy {
        ImaSdkFactory.getInstance().createImaSdkSettings().apply {
            language = adContainer.context.resources.configuration.locale.toString()
            autoPlayAdBreaks = false
        }
    }

    private val adEventListener: AdEvent.AdEventListener by lazy {
        AdEvent.AdEventListener { adEvent ->
            currentAdEvent = adEvent
            when (currentAdEvent?.type) {
                AdEvent.AdEventType.LOADED -> {
                    ExternalAdPlayer.logger?.d(TAG, "AdEvent.AdEventType.LOADED")
                    adPlayerListener.onExternalAdLoaded()
                }
                AdEvent.AdEventType.CONTENT_PAUSE_REQUESTED -> {
                    ExternalAdPlayer.logger?.d(TAG, "AdEvent.AdEventType.CONTENT_PAUSE_REQUESTED")
                    adPlayerListener.onExternalAdStarted(false)
                }
                AdEvent.AdEventType.PAUSED -> {
                    stopLoadingTimeoutJob()
                    ExternalAdPlayer.logger?.d(TAG, "AdEvent.AdEventType.PAUSED")
                }
                AdEvent.AdEventType.RESUMED -> {
                    startLoadingTimeoutJob()
                    ExternalAdPlayer.logger?.d(TAG, "AdEvent.AdEventType.RESUMED")
                    adPlayerListener.onExternalAdStarted(true)
                }
                AdEvent.AdEventType.ALL_ADS_COMPLETED -> {
                    ExternalAdPlayer.logger?.d(TAG, "AdEvent.AdEventType.ALL_ADS_COMPLETED")
                    adFinished()
                }
                AdEvent.AdEventType.AD_PROGRESS -> {
                    if (BuildConfig.DEBUG) {
                        ExternalAdPlayer.logger?.d(TAG, "AdEvent.AdEventType.AD_PROGRESS")
                    }
                    stopLoadingTimeoutJob()
                    startLoadingTimeoutJob()
                }
                AdEvent.AdEventType.SKIPPABLE_STATE_CHANGED -> {
                    ExternalAdPlayer.logger?.d(TAG, "AdEvent.AdEventType.SKIPPABLE_STATE_CHANGED")
                    if (adEvent.ad.isSkippable) {
                        adsManager?.focus()
                    }
                }
                else -> ExternalAdPlayer.logger?.d(TAG, currentAdEvent?.type.toString())
            }
        }
    }

    private val adErrorListener: AdErrorEvent.AdErrorListener by lazy {
        AdErrorEvent.AdErrorListener {
            val errorCode = it.error.errorCode
            val errorType = it.error.errorType
            val errorMsg = it.error.message
            val errorNumber = errorCode.errorNumber
            ExternalAdPlayer.logger?.e(
                TAG,
                "ad=$ad, errorCode=$errorCode, errorType=$errorType, errorNumber=$errorNumber errorMsg=$errorMsg currentAdEvent=$currentAdEvent"
            )
            when (errorType) {
                AdError.AdErrorType.LOAD -> {
                    adPlayerListener.onExternalAdLoadError(errorNumber)
                    release()
                }
                else -> {
                    adPlayerListener.onExternalAdPlayError(errorNumber)
                    release()
                }
            }
        }
    }

    private val adsLoadedListener: AdsLoader.AdsLoadedListener by lazy {
        AdsLoader.AdsLoadedListener {
            val render = ImaSdkFactory.getInstance().createAdsRenderingSettings().apply {
                enablePreloading = true
                mimeTypes = listOf(
                    "video/mp4",
                    "video/webm"
                )
                // from IMA 3.20.0
                // For CTV devices, ads are now auto focused when the AdEvent.AdEventType STARTED event is fired.
                // To disable auto focus for ads, use the adsRenderingSettings.setFocusSkipButtonWhenAvailable(false)
                // method and then use the focus() method based on the custom requirements.
                focusSkipButtonWhenAvailable = false
                setLoadVideoTimeout(VAST_TIMEOUT)
            }
            try {
                adsManager = it.adsManager.apply {
                    addAdEventListener(adEventListener)
                    addAdErrorListener(adErrorListener)
                    init(render)
                    takeIf { ad?.isMiddle == false }?.start()
                }
            } catch (exp: Exception) {
                ExternalAdPlayer.logger?.e(
                    TAG,
                    "adsManager apply start exp = $exp" + "currentAdEvent?.type = " + currentAdEvent?.type?.name,
                    exp,
                    "Google Ad Url",
                    ad?.url ?: "null"
                )
                adFinished()
            }

        }
    }

    override fun init(
        view: ViewGroup,
        overlayViewList: List<View>?,
        adPlayerListener: ExternalAdPlayer.ExternalAdPlayerListener
    ) {
        this.adContainer = view
        this.overlayViewList = overlayViewList
        this.adPlayerListener = adPlayerListener
    }

    override fun start(ad: Ad) {
        isPlaying = true
        this.ad = ad
        when (ad.isMiddle) {
            true -> when (isLoaded()) {
                true -> {
                    try {
                        adsManager?.start()
                    } catch (exp: Exception) {
                        ExternalAdPlayer.logger?.e(
                            TAG,
                            "adsManager start exp = $exp" + "currentAdEvent?.type = " + currentAdEvent?.type?.name,
                            exp,
                            "Google Ad Url",
                            ad.url
                        )
                        adFinished()
                    }
                }
                else -> adFinished()
            }
            else -> initAdsLoader(ad)
        }
    }

    override fun preload(ad: Ad) {
        this.ad = ad
        initAdsLoader(ad)
    }

    override fun resume() {
        adsManager?.resume()
    }

    override fun pause() {
        adsManager?.pause()
    }

    override fun release() {
        ad = null
        currentAdEvent = null
        isPlaying = false
        adsLoader = null
        stopLoadingTimeoutJob()
        adsLoader?.removeAdErrorListener(adErrorListener)
        adsManager?.removeAdErrorListener(adErrorListener)
        adsManager?.removeAdEventListener(adEventListener)
        adsManager?.destroy()
        displayContainer?.destroy()
    }

    override fun isPlaying(): Boolean = isPlaying

    override fun isLoaded(): Boolean = when (currentAdEvent?.type) {
        AdEvent.AdEventType.AD_BREAK_READY,
        AdEvent.AdEventType.AD_BUFFERING,
        AdEvent.AdEventType.CONTENT_RESUME_REQUESTED -> true
        else -> false
    }

    private fun initAdsLoader(ad: Ad) {
        ExternalAdPlayer.logger?.d(TAG, "ad.url = ${ad.url}")
        ImaSdkFactory.getInstance().apply {
            createAdsRequest().apply {
                adTagUrl = replaceAdTag(ad.url)
                ExternalAdPlayer.logger?.d(TAG, "adTagUrl = $adTagUrl")
                setVastLoadTimeout(VAST_TIMEOUT.toFloat())
            }.also { adRequest ->
                displayContainer = createAdDisplayContainer().apply {
                    adContainer = this@GoogleAdPlayer.adContainer
                    overlayViewList?.forEach {
                        val friendlyObstruction =
                            ImaSdkFactory.getInstance().createFriendlyObstruction(
                                it,
                                FriendlyObstructionPurpose.OTHER,
                                "Customer view for ad player view"
                            )
                        registerFriendlyObstruction(friendlyObstruction)
                    }
                }

                adsLoader =
                    createAdsLoader(adContainer.context, imaSdkSettings, displayContainer).apply {
                        addAdErrorListener(adErrorListener)
                        addAdsLoadedListener(adsLoadedListener)
                        requestAds(adRequest)
                    }
            }
        }
    }

    private fun replaceAdTag(adUrl: String): String =
        adUrl.replace("correlator=", "correlator=${System.currentTimeMillis()}")

    private fun adFinished() {
        adPlayerListener.onExternalAdEnded()
        release()
    }

    // setVastLoadTimeout is invalid, it may freeze when multiple ads load failed.
    private fun startLoadingTimeoutJob() {
        loadingTimeoutJob = MainScope().launch {
            delay(VAST_TIMEOUT.toLong())
            ExternalAdPlayer.logger?.d(TAG, "customized timeout $VAST_TIMEOUT")
            adPlayerListener.onExternalAdLoadError()
            release()
        }
    }

    private fun stopLoadingTimeoutJob() {
        loadingTimeoutJob?.cancel()
        loadingTimeoutJob = null
    }

    companion object {
        private const val VAST_TIMEOUT = 8000
    }
}

**Comment by Kiro705** [comment]
Hello @linguokun1 ,

Is this happening in on the IMA Android sample apps? If so, could you please add steps to reproduce the crash.

If this crash is not specific the sample apps, I would recommend raising your issue in the [IMA technical forum](https://groups.google.com/g/ima-sdk/). This is the best place for assistance with IMA SDK specific issues.
