### ISSUE TITLE
Linear skippable preroll ad video does not play on cast device

### ISSUE THREAD

**Issue by DavidAZimmerly** [googleads/googleads-ima-android#76]
(advanced example)
cast firmware 1.52.253741
android device oneplus 9 (running android 11)

The preroll video plays on the android device, but no preroll is shown on the cast device after casting.

I see a short blip where it seemingly attempts playback, but continues with the main video.

All the other ad examples are working for me, only the linear skippable is not working.

**Comment by Kiro705** [comment]
Hello @DavidAZimmerly ,

The Cast integration for our Android samples has recently been removed. The recommended way to have client-side ads on the. Cast platform is to use [CAF native ad breaks](https://developers.google.com/cast/docs/web_receiver/ad_breaks). Please see the link for more details on that integration.

Also, please let me know if you have any follow-up questions regarding the IMA Android samples.

Thank you,
Jackson
IMA SDK team
