### ISSUE TITLE
Sample Ad not playing

### ISSUE THREAD

**Issue by pavan77** [googleads/googleads-ima-android#8]
**Tried to run the sample app in Asus Zenfone 5(ANdroid OS:4.4.2).The ad played for 2 seconds  and the following log repeats continuously**
com.google.ads.interactivemedia.v3.samples.videoplayerapp E/IMASDK﹕ Received monitor message: getViewability for invalid session id: 12988445-5cc9-4111-80e8-e35daa136905
com.google.ads.interactivemedia.v3.samples.videoplayerapp E/IMASDK﹕ Received monitor message: getViewability for invalid session id: 12988445-5cc9-4111-80e8-e35daa136905
04-05 14:25:21.509    5170-5170/com.google.ads.interactivemedia.v3.samples.videoplayerapp E/IMASDK﹕ Received monitor message: getViewability for invalid session id: 12988445-5cc9-4111-80e8-e35daa136905  

The sample ran fine in Moto-e(OS:4.4.4).

**Comment by TakumaMochizuki** [comment]
I also has the same issue, but in a different state that on my production to backpressed to leave the activity.
