### ISSUE TITLE
Include "the SDK-generated session ID for the current ads session, as initiated by a stream request." within onAdsManagerLoaded's AdsManagerLoadedEvent object.

### ISSUE THREAD

**Issue by EugenioLopez1** [googleads/googleads-ima-android#95]
### Use case description
Currently, I do not see a reliable way to map a adsLoader.requestStream(stream) execution, to its respective response. 

This issue becomes apparent in the following scenario: 
- User selects content, initiating a stream request. 
- Before onAdsManagerLoaded is triggered(in my testing this has taken all the way up to 7 seconds but usually takes around 750ms to 2000ms), User backs out and selects another content, thus initiating another stream request on the same adsLoader and same StreamManager instance.
- onAdsManagerLoaded is then triggered twice, one for each stream request. 

Being able to map which stream request onAdsManagerLoaded is being called for would be extremely beneficial in these circumstances. 

Currently, adsLoader returns a **new** "SDK-generated session ID" every time .requestStream() is fired. However, I see no utility for this, as the "SDK-generated session ID" is not returned back within onAdsManagerLoaded, and is not available via Charles when combing through the pubads request/response or any other IMA related network traffic. 

adsLoader.requestStream's "SDK-generated session ID" also does **not** match the "sid" session-ID available in charles, which adds to further moot point. 

### Proposed solution
Include the "SDK-generated session ID" returned from adsLoader.requestStream() within onAdsManagerLoaded's  AdsManagerLoadedEvent object. This way, mapping streamIDs returned from the AdsManagerLoadedEvent object is made reliably possible, and the client side is able to perform any kind of logic which keeps record of ongoing streamRequests which have not yet returned a response.

**Comment by Kiro705** [comment]
Hello @EugenioLopez1 ,

This is the IMA Android sample repo for client-side ad insertion. `adsLoader.requestStream(stream)` is specific to server-side ads (DAI).

I would recommend looking at the [Android DAI sample apps](https://github.com/googleads/googleads-ima-android) for more info on DAI stream requests. (This is less for guidance specific to this issue, but for others who find this issue when encountering Android DAI issues.)

One option may be to tear down IMA when the user backs out of a stream, and reinitiate IMA for the 2nd stream request.

If you think this use-case requires a feature request, please reach out via the [IMA technical forum](https://groups.google.com/g/ima-sdk) for support with that request.

Thank you,
Jackson
IMA SDK team

**Comment by EugenioLopez1** [comment]
Hi @Kiro705, thank you for the recommendation, i'll reach out to the technical forum.
