### ISSUE TITLE
The AdvancedExample couldn't load Ads url on android 9 (SDK 28)

### ISSUE THREAD

**Issue by apieceofcode1801** [googleads/googleads-ima-android#99]
When I run the project on Android emulator with Android 9 (Android API 28) and below, the video player which use to load the ad url has not loaded successfully.
The console logged:
`W/MediaPlayer: Couldn't open https://redirector.gvt1.com/videoplayback/id/27c79851da1a7039/itag/106/source/dclk_video_ads/requiressl/yes/acao/yes/mime/video%2Fmp4/ctier/L/ip/0.0.0.0/ipbits/0/expire/1661175226/sparams/ip,ipbits,expire,id,itag,source,requiressl,acao,mime,ctier/signature/47750C36171C30A88B7BA9DC5A036C7B1DD23FCB.5B2BADDB32A7FD6972ECCDA3F568A624C4B30DA5/key/ck2/file/file.mp4: java.io.FileNotFoundException: No content provider: https://redirector.gvt1.com/videoplayback/id/27c79851da1a7039/itag/106/source/dclk_video_ads/requiressl/yes/acao/yes/mime/video%2Fmp4/ctier/L/ip/0.0.0.0/ipbits/0/expire/1661175226/sparams/ip,ipbits,expire,id,itag,source,requiressl,acao,mime,ctier/signature/47750C36171C30A88B7BA9DC5A036C7B1DD23FCB.5B2BADDB32A7FD6972ECCDA3F568A624C4B30DA5/key/ck2/file/file.mp4`
And the UI of the example app showed:
![Screenshot_20220822_143626](https://user-images.githubusercontent.com/77617013/185865676-e4d2e4ea-c45f-4903-a307-66911aa9e7ce.png)

The team, please help to confirm this issue. 
Thank you!

**Comment by Kiro705** [comment]
Hello @apieceofcode1801 ,

I would recommend checking that your VAST tag is successfully returning ads on the [IMA VSI player](https://googleads.github.io/googleads-ima-html5/vsi/). I tried testing there and was not able to see ad playback, which suggests there may be an issue with your test tag.

Let me know if you have any questions.

Thank you,
Jackson
IMA SDK team

**Comment by apieceofcode1801** [comment]
Hi @Kiro705 Thanks for helping to review the issue.
The ad tag in the AdvancedExample is working fine on Android 10 and later and is only not playable on Android 9.
So I think the problem does not lay in the Ad tag url.

**Comment by Kiro705** [comment]
Hello @apieceofcode1801 ,

I am still having trouble seeing ads using your sample tag in any setting.

https://redirector.gvt1.com/videoplayback/id/27c79851da1a7039/itag/106/source/dclk_video_ads/requiressl/yes/acao/yes/mime/video%2Fmp4/ctier/L/ip/0.0.0.0/ipbits/0/expire/1661175226/sparams/ip,ipbits,expire,id,itag,source,requiressl,acao,mime,ctier/signature/47750C36171C30A88B7BA9DC5A036C7B1DD23FCB.5B2BADDB32A7FD6972ECCDA3F568A624C4B30DA5/key/ck2/file/file.mp4

Is it possible that it is restricted to a certain region?
